### ISSUE TITLE
Why not rewrite SSLContext to implement the BoringSSL handshake, but instead the SSL handshake process is incorporated into NetworkBackend?

### ISSUE THREAD

**Issue by dream2333** [jonatron/boringssl-python-cffi#2]
Would it be better to extract the handshake and protocol negotiation process from the backend?

**Comment by jonatron** [comment]
I honestly don't know and can't remember the details. This repo was experimental, so I'd encourage you to do your own experimentation.

**Comment by dream2333** [comment]
> I honestly don't know and can't remember the details. This repo was experimental, so I'd encourage you to do your own experimentation.

Thank you, this has been a great instructional case for me
